apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-deployment
  namespace: awesome-ns
  labels:
    app: awesomeness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: awesomeness
  template:
    metadata:
      labels:
        app: awesomeness
    spec:
      containers:
      - name: nginx
        image: anata0820/awesome-app:1.1
        ports:
        - containerPort: 80